



SELECT SALESLINE.DATAAREAID
	,SALESLINE.TENDERLINENUM 
	,SALESLINE.SALESID
	,SALESLINE.LINENUM
	,SALESLINE.ITEMID
	,InventTrans.INVENTTRANSID
	,InventTrans.INVOICEID
	,InventTrans.VOUCHER
	,InventTrans.DateStatus
	,CASE
		WHEN INVENTTRANS.STATUSISSUE = 0 THEN 'Сторно' -- в аксапте для этого статуса пусто
		WHEN INVENTTRANS.STATUSISSUE = 1 THEN 'Продано'
		WHEN INVENTTRANS.STATUSISSUE = 2 THEN 'Отпущено'
		WHEN INVENTTRANS.STATUSISSUE = 3 THEN 'Скоплектовано'
		WHEN INVENTTRANS.STATUSISSUE = 4 THEN 'Физ.резерв'
		WHEN INVENTTRANS.STATUSISSUE = 5 THEN 'Резерв.в.заказах'
		WHEN INVENTTRANS.STATUSISSUE = 6 THEN 'Заказано'
		WHEN INVENTTRANS.STATUSISSUE = 7 THEN 'Расход по предложению'
	 END AS Статус_проводки
	 ,InventTrans.QTY AS InventTrans_QTY
	 ,SUM(InventTrans.QTY) OVER (PARTITION BY SALESLINE.TENDERLINENUM) as TenderLineNum_Qty
	 ,SUM(InventTrans.QTY) OVER (PARTITION BY SALESLINE.SALESID) as Sales_Qty
	 ,SUM(InventTrans.QTY) OVER (PARTITION BY InventTrans.INVOICEID) as Invoice_Qty
	 ,ISNULL((CustInvoiceTrans.LineAmount / CustInvoiceTrans.Qty * InventTrans.QTY),0) as InventTrans_Sum -- без налога
	 ,ISNULL((CustInvoiceTrans.TAXAMOUNT / CustInvoiceTrans.Qty * InventTrans.QTY),0) as InventTrans_Sum_Tax
	 ,SUM(ISNULL((CustInvoiceTrans.LineAmount / CustInvoiceTrans.Qty * InventTrans.QTY),0)) OVER (PARTITION BY SALESLINE.TENDERLINENUM) as TenderLineNum_Sum
	 ,SUM(ISNULL((CustInvoiceTrans.LineAmount / CustInvoiceTrans.Qty * InventTrans.QTY),0)) OVER (PARTITION BY SALESLINE.SALESID) as Sales_Sum
	 ,SUM(ISNULL((CustInvoiceTrans.LineAmount / CustInvoiceTrans.Qty * InventTrans.QTY),0)) OVER (PARTITION BY InventTrans.INVOICEID) as Invoice_Sum
	 ,SUM(ISNULL((CustInvoiceTrans.TAXAMOUNT / CustInvoiceTrans.Qty * InventTrans.QTY),0)) OVER (PARTITION BY SALESLINE.TENDERLINENUM) as TenderLineNum_Tax
	 ,SUM(ISNULL((CustInvoiceTrans.TAXAMOUNT / CustInvoiceTrans.Qty * InventTrans.QTY),0)) OVER (PARTITION BY SALESLINE.SALESID) as Sales_Tax
	 ,SUM(ISNULL((CustInvoiceTrans.TAXAMOUNT / CustInvoiceTrans.Qty * InventTrans.QTY),0)) OVER (PARTITION BY InventTrans.INVOICEID) as Invoice_Tax
	 ,ISNULL(CUSTINVOICETRANSPURCHREAL31176.PurchRealPrice,0) as РВЦ
	 ,InventDim.InventLocationId
	 ,InventDim.DepartmentId
	 ,InventDim.inventBatchId
	 ,InventDim.inventSerialId
	 ,InventDim.InventGtdId_RU
	 ,InventDim.InventExpireDate
	 ,InventDim.PurchReqLineId
from SALESLINE
JOIN SALESTABLE ON SALESLINE.SALESID = SALESTABLE.SALESID
	AND SALESLINE.DATAAREAID = SALESTABLE.DATAAREAID
	AND SALESTABLE.CREATEDDATETIME > N'2022-12-31T00:00:00.000'
	AND SALESLINE.CREATEDDATETIME > N'2022-12-31T00:00:00.000'
JOIN INVENTTRANS ON SALESLINE.INVENTTRANSID = INVENTTRANS.INVENTTRANSID
	AND INVENTTRANS.DATAAREAID	= SALESLINE.DATAAREAID
	AND InventTrans.TransRefId	= SALESLINE.SALESID
	AND InventTrans.ITEMID= SALESLINE.ITEMID
	AND InventTrans.TransType	= 0
--	AND SALESLINE.TENDERLINENUM <> ''
JOIN InventDim			ON InventTrans.INVENTDIMID = InventDim.INVENTDIMID
	AND InventDim.DATAAREAID = 'vir'
LEFT JOIN CUSTINVOICETRANS ON InventTrans.INVENTTRANSID = CUSTINVOICETRANS.INVENTTRANSID
	AND InventTrans.DATAAREAID = CUSTINVOICETRANS.DATAAREAID 
	AND InventTrans.TransRefId = CUSTINVOICETRANS.SALESID
	AND InventTrans.ITEMID = CUSTINVOICETRANS.ITEMID
	AND InventTrans.INVOICEID = CUSTINVOICETRANS.INVOICEID
LEFT JOIN CUSTINVOICETRANSPURCHREAL31176 ON InventTrans.TransRefId = CUSTINVOICETRANSPURCHREAL31176.TransRefId
	AND InventTrans.INVENTDIMID		= CUSTINVOICETRANSPURCHREAL31176.INVENTDIMID
	AND InventTrans.ITEMID			= CUSTINVOICETRANSPURCHREAL31176.ITEMID
	AND InventTrans.INVENTTRANSID	= CUSTINVOICETRANSPURCHREAL31176.INVENTTRANSID
	AND InventTrans.DATAAREAID		= CUSTINVOICETRANSPURCHREAL31176.DATAAREAID
	AND InventTrans.TransType		= CUSTINVOICETRANSPURCHREAL31176.TransType
WHERE INVENTTRANS.DATAAREAID = 'SZ'
	
--	AND INVENTTRANS.STATUSISSUE = 0
	AND SALESLINE.SALESID = '00585679_069'
	--AND SALESLINE.ITEMID = '56900'
--	AND SALESLINE.TENDERLINENUM = '073787_268_0008'
ORDER BY 1,3,4
/*
SELECT p.ProductName, p.UnitPrice, s.StoreName 
FROM Products AS p WITH (NOLOCK) 
INNER JOIN Stores AS s WITH (NOLOCK) 
ON p.StoreID = s.StoreID;
	 SELECT ISNULL(column_name, 0) FROM table_name;
*/
