
USE [W_test]
GO
SELECT
	*
FROM TENDERPREREQUESTPARTICIPA31117

--SELECT * INTO в_какую_таблицу FROM из_какой_таблицы WHERE условие
-------------------------------вставка шапки предварительных заявок -----------------------
USE [W_test]
GO
DECLARE @Lastrecid17 BIGINT = 0;
SELECT
	@Lastrecid17 = ISNULL(MAX(RECID), 0)
FROM TENDERPREREQUESTPARTICIPA31117

INSERT INTO [SPB-SQL2220DBE].[W_test].[dbo].[TENDERPREREQUESTPARTICIPA31117]

	SELECT
		*
	FROM [SPB-SQLDAXDBE].[DAX2009_1].[dbo].[TENDERPREREQUESTPARTICIPA31117] AS T
	WHERE T.ACTIVEVERSION = 1
	AND T.RECID > @Lastrecid17

-------------------------------вставка строк предварительных заявок -----------------------
USE [W_test]
GO
DECLARE @Lastrecid16 BIGINT = 0;
SELECT
	@Lastrecid16 = ISNULL(MAX(RECID), 0)
FROM TENDERPREREQUESTPARTICIPA31116

INSERT INTO [SPB-SQL2220DBE].[W_test].[dbo].[TENDERPREREQUESTPARTICIPA31116]

SELECT
T16.*
from [SPB-SQLDAXDBE].[DAX2009_1].[dbo].[TENDERPREREQUESTPARTICIPA31117] AS T17	
JOIN [SPB-SQLDAXDBE].[DAX2009_1].[dbo].[TENDERPREREQUESTPARTICIPA31116] AS T16 ON T17.VERSION = T16.VERSION
	AND T17.PREREQUESTPARTICIPATETABLEID = T16.PREREQUESTPARTICIPATETABLEID
	AND T17.ActiveVersion = 1
	AND T16.RECID > @Lastrecid16

----------------------------- вставка строк карточек тендера
USE [W_test]
GO
DECLARE @LastrecidTLINE BIGINT = 0;
SELECT
	@LastrecidTLINE = ISNULL(MAX(RECID), 0)
FROM TENDERLINE

INSERT INTO [SPB-SQL2220DBE].[W_test].[dbo].[TENDERLINE]


SELECT DISTINCT TLINE.*
FROM [SPB-SQLDAXDBE].[DAX2009_1].[dbo].[TENDERPREREQUESTPARTICIPA31116] AS T16
JOIN [SPB-SQLDAXDBE].[DAX2009_1].[dbo].[TENDERLINE] AS TLINE ON T16.TenderLineNum = TLINE.LINENUM
	AND TLINE.CREATEDDATETIME > N'2021-12-31T00:00:00.000'
	AND TLINE.RECID > @LastrecidTLINE

----------------------------- вставка строк карточек тендера

USE [W_test]
GO
DECLARE @LastrecidTB BIGINT = 0;
SELECT
	@LastrecidTB = ISNULL(MAX(RECID), 0)
FROM TENDERTABLE

INSERT INTO [SPB-SQL2220DBE].[W_test].[dbo].[TENDERTABLE]


SELECT DISTINCT TB.*
FROM [SPB-SQLDAXDBE].[DAX2009_1].[dbo].[TENDERTABLE] AS TB
JOIN TENDERLINE ON TENDERLINE.TENDERTABLEID = TB.TENDERTABLEID
	AND TB.LOTSTATUS = 37 -- Исполнение
	AND TB.DEPARTMENTID = 'Госп'
	AND TB.RECID > @LastrecidTB

----------------------------- вставка справочника номенклатур

USE [W_test]
GO
DECLARE @LastrecidINV BIGINT = 0;
SELECT
	@LastrecidINV = ISNULL(MAX(RECID), 0)
FROM INVENTTABLE

INSERT INTO [SPB-SQL2220DBE].[W_test].[dbo].[INVENTTABLE]


SELECT DISTINCT INV.*
FROM [SPB-SQLDAXDBE].[DAX2009_1].[dbo].[INVENTTABLE] AS INV
JOIN TENDERLINE ON TENDERLINE.ITEMID = INV.ITEMID
	AND INV.RECID > @LastrecidINV
	
	
	
------------------------------
USE [W_test]
GO
DECLARE @Lastrecid_ BIGINT = 0;
SELECT
	@Lastrecid_ = ISNULL(MAX(RECID), 0)
FROM _____

INSERT INTO [SPB-SQL2220DBE].[W_test].[dbo].[__]


SELECT DISTINCT __.*
FROM [SPB-SQLDAXDBE].[DAX2009_1].[dbo].[__] AS __

	AND ___.RECID > @Lastrecid
	