


DECLARE @CREATEDDATETIME DATETIME, @DATAAREAID nvarchar(4);
	SET @CREATEDDATETIME = '2021-12-31T00:00:00.000';
	SET @DATAAREAID = 'SZ';


select DISTINCT TenderTable.ResponsibleManagerId as Ответственный_менеджер
	,RContractTable.DIMENSION6_ as ЦФО
--	TENDERPREREQUESTPARTICIPA31117.PREREQUESTPARTICIPATETABLEID
--	,TENDERPREREQUESTPARTICIPA31117.VERSION
	,CUSTTABLE.ACCOUNTNUM as Код_клиента
	,CUSTTABLE.NAMEALIAS as Имя_клиента
	,TENDERPREREQUESTPARTICIPA31117.TENDERTABLEID as Код_КТ
	,CASE
		WHEN TENDERTABLE.LOTSTATUS = 0 THEN 'Создан'
		WHEN TENDERTABLE.LOTSTATUS = 10 THEN 'Отклонен'
		WHEN TENDERTABLE.LOTSTATUS = 15 THEN 'Подана заявка'
		WHEN TENDERTABLE.LOTSTATUS = 20 THEN 'Проигран'
		WHEN TENDERTABLE.LOTSTATUS = 25 THEN 'Выигран'
		WHEN TENDERTABLE.LOTSTATUS = 26 THEN 'Протокол разногласий'
		WHEN TENDERTABLE.LOTSTATUS = 30 THEN 'Подписан'
		WHEN TENDERTABLE.LOTSTATUS = 35 THEN 'Заключен контракт'
		WHEN TENDERTABLE.LOTSTATUS = 37 THEN 'Исполнение'
		WHEN TENDERTABLE.LOTSTATUS = 40 THEN 'Все отгружено'
		WHEN TENDERTABLE.LOTSTATUS = 45 THEN 'Закрыто'
		WHEN TENDERTABLE.LOTSTATUS = 50 THEN 'Претензия'
	 END as Статус
	,TenderTable.TRADINGCODE as Номер_закупа
	--,CASE
	--	WHEN TENDERTABLE.TenderExecutionControlShip = 0 THEN 'Количество'
	--	WHEN TENDERTABLE.TenderExecutionControlShip = 1 THEN 'Сумма'
	-- END as Контроль_исполнения
	,TENDERPREREQUESTPARTICIPA31116.TenderLineNum as Код_строки_КТ
	,InventTable.ProdVendName as Производитель 
	,TENDERLINE.ITEMID	as Код_товара
	,InventTable.TenderInventInternationalName as MNN
	,InventTable.ItemName as Наименование_номенклатуры
	,CAST(TenderLine.ARRIVALPRICE AS NUMERIC(20,2)) as Цена_прихода
	,CAST(TenderLine.REALINPUTPRICE AS NUMERIC(20,2)) as РВЦ
	,CAST(TENDERPREREQUESTPARTICIPA31116.REQUESTPARTICIPATEQTY AS int) as Предв_заявке
	,isnull(CAST(SLINE.SalesQty AS INT),0) as Заказ
	,CAST((TENDERPREREQUESTPARTICIPA31116.REQUESTPARTICIPATEQTY - isnull(SLINE.SalesQty,0))AS int) as Недогрузы

from TENDERPREREQUESTPARTICIPA31117	
JOIN TENDERPREREQUESTPARTICIPA31116 ON TENDERPREREQUESTPARTICIPA31117.VERSION = TENDERPREREQUESTPARTICIPA31116.VERSION
	AND TENDERPREREQUESTPARTICIPA31117.PREREQUESTPARTICIPATETABLEID = TENDERPREREQUESTPARTICIPA31116.PREREQUESTPARTICIPATETABLEID
	AND TENDERPREREQUESTPARTICIPA31117.ActiveVersion = 1
JOIN TENDERLINE ON TENDERPREREQUESTPARTICIPA31116.TenderLineNum = TENDERLINE.LINENUM
	AND TENDERLINE.CREATEDDATETIME > @CREATEDDATETIME
JOIN TENDERTABLE ON TENDERLINE.TENDERTABLEID = TENDERTABLE.TENDERTABLEID
	AND TENDERTABLE.LOTSTATUS = 37 -- Исполнение
	AND TenderTable.DEPARTMENTID = 'Госп'
--LEFT JOIN TenderExtendedProperties ON TENDERTABLE.TENDERTABLEID = TenderExtendedProperties.TENDERTABLEID --контроль исполнения
JOIN INVENTTABLE ON TENDERLINE.ITEMID = INVENTTABLE.ITEMID
JOIN CUSTTABLE ON TenderTable.CustAccount = CUSTTABLE.ACCOUNTNUM
JOIN RContractTable ON TENDERPREREQUESTPARTICIPA31117.TENDERTABLEID = RContractTable.TenderTableId
--	AND RContractTable.DATAAREAID = @DATAAREAID
	AND RContractTable.ContractEndDate < = '2023-12-31T00:00:00.000'
--	AND RContractTable.DIMENSION6_ = 'ЦФО17.1.2'
LEFT JOIN (

		select 
			SALESLINE.SALESID
			,SALESLINE.TENDERLINENUM
			,SALESLINE.ITEMID
			,SALESLINE.INVENTTRANSID
			--,CASE
			--	WHEN INVENTTRANS.STATUSISSUE = 0 THEN ''
			--	WHEN INVENTTRANS.STATUSISSUE = 1 THEN 'Продано'
			--	WHEN INVENTTRANS.STATUSISSUE = 2 THEN 'Отпущено'
			--	WHEN INVENTTRANS.STATUSISSUE = 3 THEN 'Скоплектовано'
			--	WHEN INVENTTRANS.STATUSISSUE = 4 THEN 'Физ.резерв'
			--	WHEN INVENTTRANS.STATUSISSUE = 5 THEN 'Резерв.в.заказах'
			--	WHEN INVENTTRANS.STATUSISSUE = 6 THEN 'Заказано'
			--	WHEN INVENTTRANS.STATUSISSUE = 7 THEN 'Расход по предложению'
			-- END
			 ,InventTrans.QTY
			 ,SUM(InventTrans.QTY*-1) OVER (PARTITION BY SALESLINE.TENDERLINENUM ORDER BY SALESLINE.TENDERLINENUM) as SalesQty
		from SALESLINE
		JOIN INVENTTRANS ON SALESLINE.INVENTTRANSID = INVENTTRANS.INVENTTRANSID
			AND INVENTTRANS.DATAAREAID	= SALESLINE.DATAAREAID
			AND InventTrans.TransRefId	= SALESLINE.SALESID
			AND InventTrans.ITEMID		= SALESLINE.ITEMID
			AND InventTrans.TransType	= 0
		WHERE INVENTTRANS.DATAAREAID = 'SZ'
--		AND SALESLINE.TENDERLINENUM = '073167_268_0002'

		) as SLINE ON TENDERLINE.LINENUM = SLINE.TENDERLINENUM
--WHERE TENDERPREREQUESTPARTICIPA31117.TENDERTABLEID = '073167_268'