/*
SELECT		TABLE_NAME AS [Имя таблицы],
			COLUMN_NAME AS [Имя столбца],
			DATA_TYPE AS [Тип данных столбца],
			CHARACTER_MAXIMUM_LENGTH,
			IS_NULLABLE AS [Значения NULL]
   FROM INFORMATION_SCHEMA.COLUMNS
WHERE table_name='TenderTable'
order by 2
*/

DECLARE @CREATEDDATETIME DATETIME;
	SET @CREATEDDATETIME = '2021-12-31T00:00:00.000'

select 
	TENDERTABLE.TENDERTABLEID as Код_КТ
	,TenderTable.TenderRequestCustId as Код_Заявки
	,CASE
		WHEN TENDERTABLE.LOTSTATUS = 0 THEN 'Создан'
		WHEN TENDERTABLE.LOTSTATUS = 10 THEN 'Отклонен'
		WHEN TENDERTABLE.LOTSTATUS = 15 THEN 'Подана заявка'
		WHEN TENDERTABLE.LOTSTATUS = 20 THEN 'Проигран'
		WHEN TENDERTABLE.LOTSTATUS = 25 THEN 'Выигран'
		WHEN TENDERTABLE.LOTSTATUS = 26 THEN 'Протокол разногласий'
		WHEN TENDERTABLE.LOTSTATUS = 30 THEN 'Подписан'
		WHEN TENDERTABLE.LOTSTATUS = 35 THEN 'Заключен контракт'
		WHEN TENDERTABLE.LOTSTATUS = 37 THEN 'Исполнение'
		WHEN TENDERTABLE.LOTSTATUS = 40 THEN 'Все отгружено'
		WHEN TENDERTABLE.LOTSTATUS = 45 THEN 'Закрыто'
		WHEN TENDERTABLE.LOTSTATUS = 50 THEN 'Претензия'
	 END as Статус
	,TenderTable.TRADINGCODE as Номер_закупа
	,TenderTable.CustAccount as Код_Клиента_по_КТ
	,CUSTTABLE.NAMEALIAS as Краткое_наименование_Клиента
	,TenderTable.DIMENSION6_ as ЦФО
	,TenderTable.ResponsibleManagerId as Менеджер_КТ
	,RCONTRACTTABLE.DATAAREAID as Компания
	,RContractTable.RContractAccount as Рег_номер
	,RContractTable.RContractNumber as Номер_договора
	,CONVERT(date,RContractTable.ContractStartDate,103) as Дата_начала_контракта
	,CONVERT(date,RContractTable.ContractEndDate,103) as Дата_окончания_контракта
	,CASE
		WHEN TENDERTABLE.TenderExecutionControlShip = 0 THEN 'Количество'
		WHEN TENDERTABLE.TenderExecutionControlShip = 1 THEN 'Сумма'
	 END as Контроль_исполнения
	,TENDERPREREQUEST.Кол_во_в_предв_заявке
--	COUNT(NULLIF(CustInvoiceTrans.Qty,''))	
	,INVOICE.Кол_во as Продано_Кол_во
	,CAST(TenderTable.ContractWinAmount AS NUMERIC(20,2)) as Сумма_контракта_КТ
	,INVOICE.Сумма_c_НДС as Продано_Сумма_с_НДС
	--,CASE 
	--	WHEN TENDERTABLE.TenderExecutionControlShip = 0 THEN (TENDERPREREQUEST.Кол_во_в_предв_заявке - INVOICE.Кол_во) ELSE (TenderTable.ContractWinAmount - INVOICE.Сумма_c_НДС)
	--END as Отклонения

from TENDERTABLE
LEFT JOIN (
	SELECT
		SALESTABLE.TENDERTABLEID
		,CAST(SUM(CustInvoiceTrans.Qty) AS NUMERIC(20,0)) as Кол_во
		,CAST(SUM(SalesTable.AmountTotalExclTax) AS NUMERIC(20,2)) as Сумма_без_НДС
		,CAST(SUM(SalesTable.TaxAmountTotal) AS NUMERIC(20,2)) as Сумма_НДС
		,CAST(SUM(SalesTable.AmountTotal) AS NUMERIC(20,2)) as Сумма_c_НДС
	FROM SALESTABLE 
	LEFT JOIN CUSTINVOICEJOUR ON SALESTABLE.SALESID = CUSTINVOICEJOUR.SALESID
		AND SALESTABLE.DATAAREAID = CUSTINVOICEJOUR.DATAAREAID
	LEFT JOIN CustInvoiceTrans	ON CustInvoiceJour.INVOICEID = CUSTINVOICETRANS.INVOICEID 
		AND CustInvoiceJour.SALESID				= CUSTINVOICETRANS.SALESID
		AND CustInvoiceJour.INVOICEDATE			= CUSTINVOICETRANS.INVOICEDATE
		AND CustInvoiceJour.NUMBERSEQUENCEGROUP = CUSTINVOICETRANS.NUMBERSEQUENCEGROUP
		AND CustInvoiceJour.DATAAREAID			= CUSTINVOICETRANS.DATAAREAID
	WHERE SalesTable.SZ_InventTransfer =0
		AND SalesTable.CREATEDDATETIME > @CREATEDDATETIME
	GROUP BY SALESTABLE.DATAAREAID ,SALESTABLE.TENDERTABLEID
		) as INVOICE ON TENDERTABLE.TENDERTABLEID = INVOICE.TENDERTABLEID

LEFT JOIN CUSTTABLE ON TenderTable.CustAccount = CUSTTABLE.ACCOUNTNUM
LEFT JOIN TenderExtendedProperties ON TENDERTABLE.TENDERTABLEID = TenderExtendedProperties.TENDERTABLEID
LEFT JOIN (
	select TENDERPREREQUESTPARTICIPA31117.PREREQUESTPARTICIPATETABLEID
		,TENDERPREREQUESTPARTICIPA31117.VERSION
		,TENDERPREREQUESTPARTICIPA31117.TENDERTABLEID
		,CAST(SUM(TENDERPREREQUESTPARTICIPA31116.REQUESTPARTICIPATEQTY) AS bigint) as Кол_во_в_предв_заявке 
	from TENDERPREREQUESTPARTICIPA31117	
	JOIN TENDERPREREQUESTPARTICIPA31116 ON TENDERPREREQUESTPARTICIPA31117.VERSION = TENDERPREREQUESTPARTICIPA31116.VERSION
		AND TENDERPREREQUESTPARTICIPA31117.PREREQUESTPARTICIPATETABLEID = TENDERPREREQUESTPARTICIPA31116.PREREQUESTPARTICIPATETABLEID
		AND TENDERPREREQUESTPARTICIPA31117.ActiveVersion = 1
	GROUP BY TENDERPREREQUESTPARTICIPA31117.PREREQUESTPARTICIPATETABLEID,TENDERPREREQUESTPARTICIPA31117.VERSION,TENDERPREREQUESTPARTICIPA31117.TENDERTABLEID
		) as TENDERPREREQUEST ON TENDERTABLE.TENDERTABLEID = TENDERPREREQUEST.TENDERTABLEID	
LEFT JOIN RContractTable ON TENDERTABLE.TENDERTABLEID = RContractTable.TenderTableId			
WHERE
	TENDERTABLE.CREATEDDATETIME > @CREATEDDATETIME
	AND TENDERTABLE.LOTSTATUS NOT IN (0,10,20,45)
	AND TenderTable.DIMENSION6_ IN ('ЦФО17.1','ЦФО17.1.1','ЦФО17.1.2','ЦФО17.1.3')
	






