/*
SELECT		TABLE_NAME AS [Имя таблицы],
			COLUMN_NAME AS [Имя столбца],
			DATA_TYPE AS [Тип данных столбца],
			CHARACTER_MAXIMUM_LENGTH,
			IS_NULLABLE AS [Значения NULL],
			COLUMN_DEFAULT
   FROM INFORMATION_SCHEMA.COLUMNS
WHERE table_name='INVENTTRANS'
order by 2
*/
SELECT DISTINCT 
	INVENTTRANS.DATAAREAID 
	,VENDINVOICEJOUR.INVOICEID 
	,INVENTTRANS.ITEMID
	--,INVENTBATCH.INVENTBATCHID
	--,CASE
	--	WHEN INVENTTRANS.STATUSISSUE = 0 THEN 'Корректировка'
	--	WHEN INVENTTRANS.STATUSISSUE = 1 THEN 'Продано'
	--	WHEN INVENTTRANS.STATUSISSUE = 2 THEN 'Отпущено'
	--	WHEN INVENTTRANS.STATUSISSUE = 3 THEN 'Скоплектовано'
	--	WHEN INVENTTRANS.STATUSISSUE = 4 THEN 'Физ.резерв'
	--	WHEN INVENTTRANS.STATUSISSUE = 5 THEN 'Резерв.в.заказах'
	--	WHEN INVENTTRANS.STATUSISSUE = 6 THEN 'Заказано'
	--	WHEN INVENTTRANS.STATUSISSUE = 7 THEN 'Расход по предложению'
	--END AS Status
	,VENDINVOICETRANS.INVOICEDATE
	,VENDINVOICETRANS.PURCHPRICE
	,PURCHREALPRICETABLE.PurchRealPrice
FROM INVENTTRANS
JOIN VENDINVOICETRANS 
	ON INVENTTRANS.INVENTTRANSID = INVENTTRANS.INVENTTRANSID
JOIN VENDINVOICEJOUR
	ON VENDINVOICETRANS.INVOICEID = VENDINVOICEJOUR.INVOICEID
		AND VENDINVOICETRANS.INVOICEDATE = VENDINVOICEJOUR.INVOICEDATE
JOIN INVENTDIM
	ON INVENTTRANS.INVENTDIMID = INVENTDIM.INVENTDIMID
JOIN INVENTBATCH
	ON INVENTDIM.INVENTBATCHID = INVENTBATCH.INVENTBATCHID
JOIN PURCHREALPRICETABLE
	ON VENDINVOICETRANS.INVENTTRANSID = PURCHREALPRICETABLE.INVENTTRANSID
WHERE  VENDINVOICETRANS.INVOICEDATE BETWEEN '2023-01-01T00:00:00.000' AND '2023-08-31T00:00:00.000'
	AND VendInvoiceJour.InvoiceAccount = 'П000909'
	AND VendInvoiceJour.RContractAccount = 'ДГ00023668'
	AND VENDINVOICETRANS.PURCHPRICE = 1658
	AND INVENTTRANS.ITEMID = '66252'
	AND INVENTTRANS.DATAAREAID = 'SZ'
	AND INVENTBATCH.INVENTBATCHID = '00100268_105-05802819_130'