USE [W_test]
GO

/****** Object:  Table [dbo].[bCustTable]    Script Date: 24.05.2023 11:21:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[bCustTable](
	[ACCOUNTNUM] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](200) NOT NULL,
	[ADDRESS] [nvarchar](250) NOT NULL,
	[PHONE] [nvarchar](20) NOT NULL,
	[TELEFAX] [nvarchar](20) NOT NULL,
	[INVOICEACCOUNT] [nvarchar](20) NOT NULL,
	[CUSTGROUP] [nvarchar](20) NOT NULL,
	[LINEDISC] [nvarchar](20) NOT NULL,
	[PAYMTERMID] [nvarchar](20) NOT NULL,
	[CASHDISC] [nvarchar](20) NOT NULL,
	[CURRENCY] [nvarchar](3) NOT NULL,
	[SALESGROUP] [nvarchar](20) NOT NULL,
	[BLOCKED] [int] NOT NULL,
	[ONETIMECUSTOMER] [int] NOT NULL,
	[ACCOUNTSTATEMENT] [int] NOT NULL,
	[CREDITMAX] [numeric](28, 12) NOT NULL,
	[MANDATORYCREDITLIMIT] [int] NOT NULL,
	[DIMENSION] [nvarchar](20) NOT NULL,
	[DIMENSION2_] [nvarchar](20) NOT NULL,
	[DIMENSION3_] [nvarchar](20) NOT NULL,
	[DIMENSION4_] [nvarchar](20) NOT NULL,
	[DIMENSION5_] [nvarchar](20) NOT NULL,
	[DIMENSION6_] [nvarchar](20) NOT NULL,
	[VENDACCOUNT] [nvarchar](20) NOT NULL,
	[TELEX] [nvarchar](20) NOT NULL,
	[PRICEGROUP] [nvarchar](20) NOT NULL,
	[MULTILINEDISC] [nvarchar](20) NOT NULL,
	[ENDDISC] [nvarchar](20) NOT NULL,
	[VATNUM] [nvarchar](20) NOT NULL,
	[COUNTRYREGIONID] [nvarchar](20) NOT NULL,
	[INVENTLOCATION] [nvarchar](20) NOT NULL,
	[DLVTERM] [nvarchar](20) NOT NULL,
	[DLVMODE] [nvarchar](20) NOT NULL,
	[MARKUPGROUP] [nvarchar](20) NOT NULL,
	[CLEARINGPERIOD] [nvarchar](20) NOT NULL,
	[ZIPCODE] [nvarchar](10) NOT NULL,
	[STATE] [nvarchar](20) NOT NULL,
	[COUNTY] [nvarchar](20) NOT NULL,
	[URL] [nvarchar](300) NOT NULL,
	[EMAIL] [nvarchar](80) NOT NULL,
	[CELLULARPHONE] [nvarchar](20) NOT NULL,
	[PHONELOCAL] [nvarchar](10) NOT NULL,
	[FREIGHTZONE] [nvarchar](20) NOT NULL,
	[CREDITRATING] [nvarchar](10) NOT NULL,
	[TAXGROUP] [nvarchar](20) NOT NULL,
	[STATISTICSGROUP] [nvarchar](20) NOT NULL,
	[PAYMMODE] [nvarchar](20) NOT NULL,
	[COMMISSIONGROUP] [nvarchar](20) NOT NULL,
	[BANKACCOUNT] [nvarchar](10) NOT NULL,
	[PAYMSCHED] [nvarchar](30) NOT NULL,
	[NAMEALIAS] [nvarchar](200) NOT NULL,
	[CONTACTPERSONID] [nvarchar](20) NOT NULL,
	[INVOICEADDRESS] [int] NOT NULL,
	[OURACCOUNTNUM] [nvarchar](20) NOT NULL,
	[SALESPOOLID] [nvarchar](20) NOT NULL,
	[INCLTAX] [int] NOT NULL,
	[CUSTITEMGROUPID] [nvarchar](20) NOT NULL,
	[NUMBERSEQUENCEGROUP] [nvarchar](20) NOT NULL,
	[LANGUAGEID] [nvarchar](7) NOT NULL,
	[PAYMDAYID] [nvarchar](20) NOT NULL,
	[LINEOFBUSINESSID] [nvarchar](20) NOT NULL,
	[DESTINATIONCODEID] [nvarchar](20) NOT NULL,
	[GIROTYPE] [int] NOT NULL,
	[SUPPITEMGROUPID] [nvarchar](20) NOT NULL,
	[GIROTYPEINTERESTNOTE] [int] NOT NULL,
	[TAXLICENSENUM] [nvarchar](20) NOT NULL,
	[PAYMSPEC] [nvarchar](20) NOT NULL,
	[BANKCENTRALBANKPURPOSETEXT] [nvarchar](400) NOT NULL,
	[BANKCENTRALBANKPURPOSECODE] [nvarchar](10) NOT NULL,
	[CITY] [nvarchar](200) NOT NULL,
	[STREET] [nvarchar](250) NOT NULL,
	[PAGER] [nvarchar](20) NOT NULL,
	[SMS] [nvarchar](80) NOT NULL,
	[PACKMATERIALFEELICENSENUM] [nvarchar](20) NOT NULL,
	[DLVREASON] [nvarchar](20) NOT NULL,
	[GIROTYPECOLLECTIONLETTER] [int] NOT NULL,
	[SALESCALENDARID] [nvarchar](10) NOT NULL,
	[CUSTCLASSIFICATIONID] [nvarchar](20) NOT NULL,
	[SHIPCARRIERACCOUNT] [nvarchar](25) NOT NULL,
	[GIROTYPEPROJINVOICE] [int] NOT NULL,
	[INVENTSITEID] [nvarchar](10) NOT NULL,
	[ORDERENTRYDEADLINEGROUPID] [nvarchar](20) NOT NULL,
	[SHIPCARRIERID] [nvarchar](10) NOT NULL,
	[SHIPCARRIERFUELSURCHARGE] [int] NOT NULL,
	[SHIPCARRIERBLINDSHIPMENT] [int] NOT NULL,
	[PARTYTYPE] [int] NOT NULL,
	[PARTYID] [nvarchar](20) NOT NULL,
	[SHIPCARRIERACCOUNTCODE] [nvarchar](20) NOT NULL,
	[PROJPRICEGROUP] [nvarchar](20) NOT NULL,
	[GIROTYPEFREETEXTINVOICE] [int] NOT NULL,
	[SYNCENTITYID] [uniqueidentifier] NOT NULL,
	[SYNCVERSION] [bigint] NOT NULL,
	[RFIDITEMTAGGING] [int] NOT NULL,
	[RFIDCASETAGGING] [int] NOT NULL,
	[RFIDPALLETTAGGING] [int] NOT NULL,
	[IDENTIFICATIONNUMBER] [nvarchar](50) NOT NULL,
	[PARTYCOUNTRY] [nvarchar](20) NOT NULL,
	[PARTYSTATE] [nvarchar](20) NOT NULL,
	[GIROTYPEACCOUNTSTATEMENT] [int] NOT NULL,
	[INVENTPROFILETYPE_RU] [int] NOT NULL,
	[INVENTPROFILEID_RU] [nvarchar](20) NOT NULL,
	[INVOICEPOSTINGTYPE_RU] [int] NOT NULL,
	[FOREIGNRESIDENT_RU] [int] NOT NULL,
	[INN_RU] [nvarchar](12) NOT NULL,
	[CODEOKPO_RU] [nvarchar](10) NOT NULL,
	[CODEOKDP_RU] [nvarchar](8) NOT NULL,
	[KPP_RU] [nvarchar](9) NOT NULL,
	[OKATO_RU] [nvarchar](11) NOT NULL,
	[TOWNID_RU] [nvarchar](10) NOT NULL,
	[SETTLEMENTID_RU] [nvarchar](10) NOT NULL,
	[STREETID_RU] [nvarchar](10) NOT NULL,
	[FLAT_RU] [nvarchar](10) NOT NULL,
	[BUILDING_RU] [nvarchar](10) NOT NULL,
	[ESTATE_RU] [nvarchar](10) NOT NULL,
	[REGNUM_W] [nvarchar](15) NOT NULL,
	[RAILWAYCODE] [int] NOT NULL,
	[RCONTRACTCODEDEFAULT] [nvarchar](10) NOT NULL,
	[RCONTRACTACCOUNTDEFAULT] [nvarchar](10) NOT NULL,
	[RCONTRACTCODESAFETYDEPOSIT] [nvarchar](10) NOT NULL,
	[RCONTRACTACCOUNTSAFETYDEPOSIT] [nvarchar](10) NOT NULL,
	[RCONTRACTCODETOLLING] [nvarchar](10) NOT NULL,
	[RCONTRACTACCOUNTTOLLING] [nvarchar](10) NOT NULL,
	[NOTVALIDINN] [int] NOT NULL,
	[RCONTRACTNUMNECESSITY] [int] NOT NULL,
	[EXPORT] [int] NOT NULL,
	[ISAGENTFEE] [int] NOT NULL,
	[AGENTFEEPERCENT] [numeric](28, 12) NOT NULL,
	[CANSETTLESAMERCONTRACT] [int] NOT NULL,
	[ALLOWOPERATIONSWITHOUTRCO30001] [int] NOT NULL,
	[CREDITLIMITEXCESSPCT] [numeric](28, 12) NOT NULL,
	[CHECKDEBTS] [int] NOT NULL,
	[ACCEPTABLEDEBTSPERIOD] [int] NOT NULL,
	[ACCEPTABLESHIPMENTAMOUNT] [numeric](28, 12) NOT NULL,
	[REMAINEDEXPIREPERIOD] [int] NOT NULL,
	[NOTALLOWDIFFLOCATIONSFORP30009] [int] NOT NULL,
	[FICTRESERVEDAYS] [int] NOT NULL,
	[ISHOLDING] [int] NOT NULL,
	[HOLDINGCUSTACCOUNT] [nvarchar](20) NOT NULL,
	[LOGISTICMAXWEIGHTONPALLET] [numeric](28, 12) NOT NULL,
	[LOGISTICMAXHEIGHTONPALLET] [numeric](28, 12) NOT NULL,
	[LOGISTICPALLETSTYPE] [nvarchar](20) NOT NULL,
	[LOGISTICDIFFERENTITEMSONPALLET] [int] NOT NULL,
	[DELIVERYAREACODEID] [nvarchar](20) NOT NULL,
	[ITEMRESERVATION] [int] NOT NULL,
	[VALIDATEHOLDINGCREDITLIMIT] [int] NOT NULL,
	[SHOPNUM] [nvarchar](30) NOT NULL,
	[GLNNUMBER] [nvarchar](30) NOT NULL,
	[TARERETURN] [int] NOT NULL,
	[ALLOWEDTAREDEBT] [int] NOT NULL,
	[RESPONSIBLEMANAGER] [nvarchar](20) NOT NULL,
	[EXTERNALITEMUNIT] [int] NOT NULL,
	[GENERALNAME] [nvarchar](200) NOT NULL,
	[EARLYASSEMBLY] [int] NOT NULL,
	[ASSEMBLYPERIOD] [int] NOT NULL,
	[INVOICE4PAYMTERM] [int] NOT NULL,
	[DEFAULTRESERVEPERIOD] [datetime] NOT NULL,
	[ISRETAIL] [int] NOT NULL,
	[RETAILCUSTACCOUNT] [nvarchar](20) NOT NULL,
	[CHECKVALIDITYCERTIFICATES] [int] NOT NULL,
	[NREC] [bigint] NOT NULL,
	[ALLOWCROSSDOCKING] [int] NOT NULL,
	[PACKNORMCHECK] [int] NOT NULL,
	[ELINVOICEFORMAT] [int] NOT NULL,
	[ELINVOICESENDMAIL] [int] NOT NULL,
	[ELINVOICEEMAIL] [nvarchar](80) NOT NULL,
	[ELPRICELISTEMAIL] [nvarchar](80) NOT NULL,
	[ELPRICELISTFORMAT] [int] NOT NULL,
	[REFUSINGEMAIL] [nvarchar](80) NOT NULL,
	[ELPRICELISTSENDMAIL] [int] NOT NULL,
	[EMAILID] [nvarchar](10) NOT NULL,
	[RISKCATEGORY] [int] NOT NULL,
	[LOGISTICROUTEID] [nvarchar](40) NOT NULL,
	[TENDERPREREQUESTEXPORTTEM30051] [nvarchar](40) NOT NULL,
	[IMPORTSINGLEORDERINADAY] [int] NOT NULL,
	[FTPSEND] [int] NOT NULL,
	[FTPPASSWORD] [nvarchar](20) NOT NULL,
	[FTPLOGIN] [nvarchar](100) NOT NULL,
	[FTPPATH] [nvarchar](300) NOT NULL,
	[FTPDOMAIN] [nvarchar](100) NOT NULL,
	[PRICELISTFTPSEND] [int] NOT NULL,
	[PRICELISTFTPPASSWORD] [nvarchar](20) NOT NULL,
	[PRICELISTFTPLOGIN] [nvarchar](100) NOT NULL,
	[PRICELISTFTPPATH] [nvarchar](300) NOT NULL,
	[PRICELISTFTPDOMAIN] [nvarchar](100) NOT NULL,
	[DEMANDEXPTOWMS] [int] NOT NULL,
	[CODEA] [nvarchar](20) NOT NULL,
	[MODIFIEDDATETIME] [datetime] NOT NULL,
	[CREATEDDATETIME] [datetime] NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[RECVERSION] [int] NOT NULL,
	[RECID] [bigint] NOT NULL,
	[SZ_MAPPINGREFRECID] [bigint] NOT NULL,
	[SZ_GUID1C] [uniqueidentifier] NOT NULL,
	[SZ_NREC] [nvarchar](50) NOT NULL,
	[MODIFIEDBY] [nvarchar](5) NOT NULL,
	[CREATEDBY] [nvarchar](5) NOT NULL,
	[SZ_NOTGROUPBYCONSIGNEE] [int] NOT NULL,
	[DBFEXPORTMP] [nvarchar](259) NOT NULL,
	[SZ_EMPL] [int] NOT NULL,
	[SZ_PRINTTRANSFERDOCUMENTS] [int] NOT NULL,
	[SZ_REFUSEFORMAT] [int] NOT NULL,
	[SZ_REFUSEFTPSEND] [int] NOT NULL,
	[SZ_REFUSEFTPPASSWORD] [nvarchar](20) NOT NULL,
	[SZ_REFUSEFTPLOGIN] [nvarchar](100) NOT NULL,
	[SZ_REFUSEFTPPATH] [nvarchar](300) NOT NULL,
	[SZ_NOTGROUPBYINVENT] [int] NOT NULL,
	[MP] [int] NOT NULL,
	[JURIDICALCODE] [nvarchar](15) NOT NULL,
	[LICENSENUM] [nvarchar](50) NOT NULL,
	[LICENSETYPE] [int] NOT NULL,
	[LICENSESTARTDATE] [datetime] NOT NULL,
	[LICENSEENDDATE] [datetime] NOT NULL,
	[VIRTUALCOMPANYMP] [nvarchar](4) NOT NULL,
	[SZ_CONTRACTCONSIGNEE] [nvarchar](250) NOT NULL,
	[SZ_ISFILIAL] [int] NOT NULL,
	[DRUGSTORE] [int] NOT NULL,
	[SZ_PERIODACTRECONCILIATION] [int] NOT NULL,
	[SZ_TRANSFERGOODSINVOICE] [int] NOT NULL,
	[SZ_OGRN] [nvarchar](15) NOT NULL,
	[SZ_LASTDATEACTRECONCILIATION] [datetime] NOT NULL,
	[SZ_CODESBIS] [nvarchar](50) NOT NULL,
	[SZ_ISNOTCONSIGNOR] [int] NOT NULL,
	[SZ_MAPPINGREFRECID_INVOICE] [bigint] NOT NULL,
	[USEMAPPINGINVOICE] [int] NOT NULL,
	[CHECKITEMADVANCEDPROPERTIES] [int] NOT NULL,
	[MAXPRICEVITALTYPE] [int] NOT NULL,
	[NOTCHECKCREDITLIMIT] [int] NOT NULL,
	[CHECKREGISTRATIONCERTIFIC50034] [int] NOT NULL,
	[RCONTRACTACCOUNTTRANSPORTATION] [nvarchar](10) NOT NULL,
	[RCONTRACTCODETRANSPORTATION] [nvarchar](10) NOT NULL,
	[CHECKMDLPCOUNTERPARTYID] [int] NOT NULL,
	[EDS] [int] NULL,
	[ElInvoiceStartDate] [datetime] NULL,
 CONSTRAINT [I_077ACCOUNTIDX] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[ACCOUNTNUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [ACCOUNTNUM]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [NAME]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [ADDRESS]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PHONE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [TELEFAX]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [INVOICEACCOUNT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CUSTGROUP]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [LINEDISC]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PAYMTERMID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CASHDISC]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CURRENCY]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SALESGROUP]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [BLOCKED]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ONETIMECUSTOMER]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ACCOUNTSTATEMENT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [CREDITMAX]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [MANDATORYCREDITLIMIT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [DIMENSION]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [DIMENSION2_]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [DIMENSION3_]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [DIMENSION4_]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [DIMENSION5_]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [DIMENSION6_]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [VENDACCOUNT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [TELEX]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PRICEGROUP]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [MULTILINEDISC]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [ENDDISC]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [VATNUM]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [COUNTRYREGIONID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [INVENTLOCATION]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [DLVTERM]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [DLVMODE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [MARKUPGROUP]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CLEARINGPERIOD]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [ZIPCODE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [STATE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [COUNTY]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [URL]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [EMAIL]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CELLULARPHONE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PHONELOCAL]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [FREIGHTZONE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CREDITRATING]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [TAXGROUP]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [STATISTICSGROUP]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PAYMMODE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [COMMISSIONGROUP]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [BANKACCOUNT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PAYMSCHED]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [NAMEALIAS]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CONTACTPERSONID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [INVOICEADDRESS]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [OURACCOUNTNUM]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SALESPOOLID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [INCLTAX]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CUSTITEMGROUPID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [NUMBERSEQUENCEGROUP]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [LANGUAGEID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PAYMDAYID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [LINEOFBUSINESSID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [DESTINATIONCODEID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [GIROTYPE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SUPPITEMGROUPID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [GIROTYPEINTERESTNOTE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [TAXLICENSENUM]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PAYMSPEC]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [BANKCENTRALBANKPURPOSETEXT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [BANKCENTRALBANKPURPOSECODE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CITY]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [STREET]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PAGER]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SMS]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PACKMATERIALFEELICENSENUM]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [DLVREASON]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [GIROTYPECOLLECTIONLETTER]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SALESCALENDARID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CUSTCLASSIFICATIONID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SHIPCARRIERACCOUNT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [GIROTYPEPROJINVOICE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [INVENTSITEID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [ORDERENTRYDEADLINEGROUPID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SHIPCARRIERID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SHIPCARRIERFUELSURCHARGE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SHIPCARRIERBLINDSHIPMENT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [PARTYTYPE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PARTYID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SHIPCARRIERACCOUNTCODE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PROJPRICEGROUP]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [GIROTYPEFREETEXTINVOICE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('{00000000-0000-0000-0000-000000000000}') FOR [SYNCENTITYID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SYNCVERSION]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [RFIDITEMTAGGING]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [RFIDCASETAGGING]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [RFIDPALLETTAGGING]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [IDENTIFICATIONNUMBER]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PARTYCOUNTRY]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PARTYSTATE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [GIROTYPEACCOUNTSTATEMENT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [INVENTPROFILETYPE_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [INVENTPROFILEID_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [INVOICEPOSTINGTYPE_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [FOREIGNRESIDENT_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [INN_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CODEOKPO_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CODEOKDP_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [KPP_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [OKATO_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [TOWNID_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SETTLEMENTID_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [STREETID_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [FLAT_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [BUILDING_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [ESTATE_RU]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [REGNUM_W]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [RAILWAYCODE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [RCONTRACTCODEDEFAULT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [RCONTRACTACCOUNTDEFAULT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [RCONTRACTCODESAFETYDEPOSIT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [RCONTRACTACCOUNTSAFETYDEPOSIT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [RCONTRACTCODETOLLING]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [RCONTRACTACCOUNTTOLLING]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [NOTVALIDINN]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [RCONTRACTNUMNECESSITY]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [EXPORT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ISAGENTFEE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [AGENTFEEPERCENT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [CANSETTLESAMERCONTRACT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ALLOWOPERATIONSWITHOUTRCO30001]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [CREDITLIMITEXCESSPCT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [CHECKDEBTS]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ACCEPTABLEDEBTSPERIOD]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ACCEPTABLESHIPMENTAMOUNT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [REMAINEDEXPIREPERIOD]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [NOTALLOWDIFFLOCATIONSFORP30009]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [FICTRESERVEDAYS]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ISHOLDING]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [HOLDINGCUSTACCOUNT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [LOGISTICMAXWEIGHTONPALLET]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [LOGISTICMAXHEIGHTONPALLET]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [LOGISTICPALLETSTYPE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [LOGISTICDIFFERENTITEMSONPALLET]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [DELIVERYAREACODEID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ITEMRESERVATION]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [VALIDATEHOLDINGCREDITLIMIT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SHOPNUM]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [GLNNUMBER]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [TARERETURN]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ALLOWEDTAREDEBT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [RESPONSIBLEMANAGER]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [EXTERNALITEMUNIT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [GENERALNAME]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [EARLYASSEMBLY]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ASSEMBLYPERIOD]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [INVOICE4PAYMTERM]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DEFAULTRESERVEPERIOD]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ISRETAIL]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [RETAILCUSTACCOUNT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [CHECKVALIDITYCERTIFICATES]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [NREC]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ALLOWCROSSDOCKING]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [PACKNORMCHECK]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ELINVOICEFORMAT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ELINVOICESENDMAIL]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [ELINVOICEEMAIL]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [ELPRICELISTEMAIL]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ELPRICELISTFORMAT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [REFUSINGEMAIL]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [ELPRICELISTSENDMAIL]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [EMAILID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [RISKCATEGORY]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [LOGISTICROUTEID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [TENDERPREREQUESTEXPORTTEM30051]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [IMPORTSINGLEORDERINADAY]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [FTPSEND]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [FTPPASSWORD]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [FTPLOGIN]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [FTPPATH]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [FTPDOMAIN]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [PRICELISTFTPSEND]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PRICELISTFTPPASSWORD]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PRICELISTFTPLOGIN]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PRICELISTFTPPATH]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [PRICELISTFTPDOMAIN]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [DEMANDEXPTOWMS]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [CODEA]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [MODIFIEDDATETIME]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [CREATEDDATETIME]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('dat') FOR [DATAAREAID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((1)) FOR [RECVERSION]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SZ_MAPPINGREFRECID]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('{00000000-0000-0000-0000-000000000000}') FOR [SZ_GUID1C]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SZ_NREC]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('?') FOR [MODIFIEDBY]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('?') FOR [CREATEDBY]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SZ_NOTGROUPBYCONSIGNEE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [DBFEXPORTMP]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SZ_EMPL]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SZ_PRINTTRANSFERDOCUMENTS]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SZ_REFUSEFORMAT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SZ_REFUSEFTPSEND]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SZ_REFUSEFTPPASSWORD]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SZ_REFUSEFTPLOGIN]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SZ_REFUSEFTPPATH]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SZ_NOTGROUPBYINVENT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [MP]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [JURIDICALCODE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [LICENSENUM]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [LICENSETYPE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [LICENSESTARTDATE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [LICENSEENDDATE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [VIRTUALCOMPANYMP]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SZ_CONTRACTCONSIGNEE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SZ_ISFILIAL]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [DRUGSTORE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SZ_PERIODACTRECONCILIATION]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SZ_TRANSFERGOODSINVOICE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SZ_OGRN]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [SZ_LASTDATEACTRECONCILIATION]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [SZ_CODESBIS]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SZ_ISNOTCONSIGNOR]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [SZ_MAPPINGREFRECID_INVOICE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [USEMAPPINGINVOICE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [CHECKITEMADVANCEDPROPERTIES]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [MAXPRICEVITALTYPE]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [NOTCHECKCREDITLIMIT]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [CHECKREGISTRATIONCERTIFIC50034]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [RCONTRACTACCOUNTTRANSPORTATION]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ('') FOR [RCONTRACTCODETRANSPORTATION]
GO

ALTER TABLE [dbo].[bCustTable] ADD  DEFAULT ((0)) FOR [CHECKMDLPCOUNTERPARTYID]
GO

ALTER TABLE [dbo].[bCustTable]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO


