USE [W_test]
GO

/****** Object:  Table [dbo].[bINVENTBATCH]    Script Date: 24.05.2023 11:23:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[bINVENTBATCH](
	[INVENTBATCHID] [nvarchar](40) NOT NULL,
	[EXPDATE] [datetime] NOT NULL,
	[ITEMID] [nvarchar](20) NOT NULL,
	[PRODDATE] [datetime] NOT NULL,
	[DESCRIPTION] [ntext] NULL,
	[BARCODESTRING] [nvarchar](70) NOT NULL,
	[PRODUCER] [nvarchar](20) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[RECVERSION] [int] NOT NULL,
	[RECID] [bigint] NOT NULL,
	[INVENTPROFILETYPE] [int] NOT NULL,
	[PRINTOUTJOURNALNUM] [nvarchar](30) NOT NULL,
	[ARRIVALDATE] [datetime] NOT NULL,
	[OWNERDATAAREA] [nvarchar](4) NOT NULL,
	[PACKNORMQTY] [int] NOT NULL,
	[SZ_VENDACCOUNT] [nvarchar](20) NOT NULL,
	[MODIFIEDDATETIME] [datetime] NOT NULL,
	[MODIFIEDBY] [nvarchar](5) NOT NULL,
	[CREATEDDATETIME] [datetime] NOT NULL,
	[CREATEDBY] [nvarchar](5) NOT NULL,
	[INVENTBATCHIDORIG] [nvarchar](40) NOT NULL,
	[MULTIPLICITY] [int] NOT NULL,
	[LASTUPDATEDATEMDLP] [datetime] NOT NULL,
 CONSTRAINT [I_752ITEMBATCHIDX] PRIMARY KEY NONCLUSTERED 
(
	[DATAAREAID] ASC,
	[ITEMID] ASC,
	[INVENTBATCHID] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('') FOR [INVENTBATCHID]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [EXPDATE]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('') FOR [ITEMID]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [PRODDATE]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT (NULL) FOR [DESCRIPTION]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('') FOR [BARCODESTRING]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('') FOR [PRODUCER]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('dat') FOR [DATAAREAID]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ((1)) FOR [RECVERSION]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ((0)) FOR [INVENTPROFILETYPE]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('') FOR [PRINTOUTJOURNALNUM]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [ARRIVALDATE]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('') FOR [OWNERDATAAREA]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ((0)) FOR [PACKNORMQTY]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('') FOR [SZ_VENDACCOUNT]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [MODIFIEDDATETIME]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('?') FOR [MODIFIEDBY]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [CREATEDDATETIME]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('?') FOR [CREATEDBY]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('') FOR [INVENTBATCHIDORIG]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ((0)) FOR [MULTIPLICITY]
GO

ALTER TABLE [dbo].[bINVENTBATCH] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [LASTUPDATEDATEMDLP]
GO

ALTER TABLE [dbo].[bINVENTBATCH]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO


