USE [W_test]
GO

/****** Object:  Table [dbo].[bINVENTDIM]    Script Date: 24.05.2023 11:24:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[bINVENTDIM](
	[INVENTDIMID] [nvarchar](30) NOT NULL,
	[INVENTBATCHID] [nvarchar](40) NOT NULL,
	[INVENTSERIALID] [nvarchar](40) NOT NULL,
	[INVENTLOCATIONID] [nvarchar](20) NOT NULL,
	[INVENTSITEID] [nvarchar](10) NOT NULL,
	[INVENTPROFILEID_RU] [nvarchar](20) NOT NULL,
	[INVENTOWNERID_RU] [nvarchar](30) NOT NULL,
	[INVENTGTDID_RU] [nvarchar](30) NOT NULL,
	[INVENTRESPPERS] [nvarchar](20) NOT NULL,
	[SUPPLYREQUESTNUM] [nvarchar](15) NOT NULL,
	[MARKETINGACTIONID] [nvarchar](30) NOT NULL,
	[INVENTEXPIREDATE] [datetime] NOT NULL,
	[DEPARTMENTID] [nvarchar](20) NOT NULL,
	[PURCHREQLINEID] [nvarchar](20) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[RECVERSION] [int] NOT NULL,
	[RECID] [bigint] NOT NULL,
	[MODIFIEDDATETIME] [datetime] NOT NULL,
	[MODIFIEDBY] [nvarchar](5) NOT NULL,
	[CREATEDDATETIME] [datetime] NOT NULL,
	[CREATEDBY] [nvarchar](5) NOT NULL,
	[BATCHTRACKTRACEID] [nvarchar](40) NOT NULL,
 CONSTRAINT [I_698DIMIDIDX] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[INVENTDIMID] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [INVENTDIMID]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [INVENTBATCHID]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [INVENTSERIALID]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [INVENTLOCATIONID]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [INVENTSITEID]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [INVENTPROFILEID_RU]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [INVENTOWNERID_RU]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [INVENTGTDID_RU]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [INVENTRESPPERS]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [SUPPLYREQUESTNUM]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [MARKETINGACTIONID]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [INVENTEXPIREDATE]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [DEPARTMENTID]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [PURCHREQLINEID]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('dat') FOR [DATAAREAID]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ((1)) FOR [RECVERSION]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [MODIFIEDDATETIME]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('?') FOR [MODIFIEDBY]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [CREATEDDATETIME]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('?') FOR [CREATEDBY]
GO

ALTER TABLE [dbo].[bINVENTDIM] ADD  DEFAULT ('') FOR [BATCHTRACKTRACEID]
GO

ALTER TABLE [dbo].[bINVENTDIM]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO


