USE [W_test]
GO

/****** Object:  Table [dbo].[bINVENTTRANS]    Script Date: 24.05.2023 11:26:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[bINVENTTRANS](
	[ITEMID] [nvarchar](20) NOT NULL,
	[STATUSISSUE] [int] NOT NULL,
	[DATEPHYSICAL] [datetime] NOT NULL,
	[QTY] [numeric](28, 12) NOT NULL,
	[COSTAMOUNTPOSTED] [numeric](28, 12) NOT NULL,
	[CURRENCYCODE] [nvarchar](3) NOT NULL,
	[TRANSTYPE] [int] NOT NULL,
	[TRANSREFID] [nvarchar](30) NOT NULL,
	[INVOICEID] [nvarchar](30) NOT NULL,
	[VOUCHER] [nvarchar](30) NOT NULL,
	[INVENTTRANSIDTRANSFER] [nvarchar](30) NOT NULL,
	[DATEEXPECTED] [datetime] NOT NULL,
	[DATEFINANCIAL] [datetime] NOT NULL,
	[COSTAMOUNTPHYSICAL] [numeric](28, 12) NOT NULL,
	[INVENTTRANSID] [nvarchar](30) NOT NULL,
	[STATUSRECEIPT] [int] NOT NULL,
	[PACKINGSLIPRETURNED] [int] NOT NULL,
	[INVOICERETURNED] [int] NOT NULL,
	[PACKINGSLIPID] [nvarchar](30) NOT NULL,
	[VOUCHERPHYSICAL] [nvarchar](30) NOT NULL,
	[COSTAMOUNTADJUSTMENT] [numeric](28, 12) NOT NULL,
	[SHIPPINGDATEREQUESTED] [datetime] NOT NULL,
	[SHIPPINGDATECONFIRMED] [datetime] NOT NULL,
	[QTYSETTLED] [numeric](28, 12) NOT NULL,
	[COSTAMOUNTSETTLED] [numeric](28, 12) NOT NULL,
	[VALUEOPEN] [int] NOT NULL,
	[DIRECTION] [int] NOT NULL,
	[DATESTATUS] [datetime] NOT NULL,
	[COSTAMOUNTSTD] [numeric](28, 12) NOT NULL,
	[DATECLOSED] [datetime] NOT NULL,
	[PICKINGROUTEID] [nvarchar](10) NOT NULL,
	[INVENTTRANSIDFATHER] [nvarchar](30) NOT NULL,
	[COSTAMOUNTOPERATIONS] [numeric](28, 12) NOT NULL,
	[ITEMBOMID] [nvarchar](20) NOT NULL,
	[INVENTTRANSIDRETURN] [nvarchar](30) NOT NULL,
	[INVENTDIMID] [nvarchar](30) NOT NULL,
	[INVENTDIMFIXED] [int] NOT NULL,
	[DATEINVENT] [datetime] NOT NULL,
	[CUSTVENDAC] [nvarchar](20) NOT NULL,
	[TRANSCHILDREFID] [nvarchar](30) NOT NULL,
	[TRANSCHILDTYPE] [int] NOT NULL,
	[REVENUEAMOUNTPHYSICAL] [numeric](28, 12) NOT NULL,
	[ASSETID] [nvarchar](20) NOT NULL,
	[TAXAMOUNTPHYSICAL] [numeric](28, 12) NOT NULL,
	[ASSETBOOKID] [nvarchar](10) NOT NULL,
	[INVENTREFTRANSID] [nvarchar](30) NOT NULL,
	[NONFINANCIALTRANSFERINVENTCL73] [bigint] NOT NULL,
	[STORNO_RU] [int] NOT NULL,
	[STORNOPHYSICAL_RU] [int] NOT NULL,
	[INVENTDIMIDSALES_RU] [nvarchar](30) NOT NULL,
	[INVENTTRANSIDSALES_RU] [nvarchar](30) NOT NULL,
	[INVENTTRANSIDTRANSIT_RU] [nvarchar](30) NOT NULL,
	[INVENTTRANSIDDELIVERY_RU] [nvarchar](30) NOT NULL,
	[GROUPREFTYPE_RU] [int] NOT NULL,
	[GROUPREFID_RU] [nvarchar](30) NOT NULL,
	[COSTAMOUNTSECCURPOSTED_RU] [numeric](28, 12) NOT NULL,
	[COSTAMOUNTSECCURPHYSICAL_RU] [numeric](28, 12) NOT NULL,
	[COSTAMOUNTSECCURADJUSTMENT_RU] [numeric](28, 12) NOT NULL,
	[DATECLOSEDSECCUR_RU] [datetime] NOT NULL,
	[QTYSETTLEDSECCUR_RU] [numeric](28, 12) NOT NULL,
	[COSTAMOUNTSETTLEDSECCUR_RU] [numeric](28, 12) NOT NULL,
	[VALUEOPENSECCUR_RU] [int] NOT NULL,
	[COSTAMOUNTSTDSECCUR_RU] [numeric](28, 12) NOT NULL,
	[CUSTVENDEMPLTYPE] [int] NOT NULL,
	[TRANSTXT] [nvarchar](300) NOT NULL,
	[PICKPAYTRANSTYPE] [int] NOT NULL,
	[RASSETQTY] [numeric](28, 12) NOT NULL,
	[FICTRESERVEDATE] [datetime] NOT NULL,
	[INVOICEEXTERNALIDCROSSDOCKING] [nvarchar](30) NOT NULL,
	[SZ_DATEREGISTRATION] [datetime] NOT NULL,
	[SZ_DATEREGISTRATIONTZID] [int] NOT NULL,
	[MODIFIEDDATETIME] [datetime] NOT NULL,
	[MODIFIEDBY] [nvarchar](5) NOT NULL,
	[CREATEDDATETIME] [datetime] NOT NULL,
	[CREATEDBY] [nvarchar](5) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[RECVERSION] [int] NOT NULL,
	[RECID] [bigint] NOT NULL,
	[SZ_DATESTATUS] [datetime] NOT NULL,
	[SZ_ISFILIAL] [int] NOT NULL,
	[SZ_ISRETAIL] [int] NOT NULL,
	[ITEMID_EXT] [nvarchar](20) NOT NULL,
 CONSTRAINT [I_177TRANSIDIDX] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[INVENTTRANSID] ASC,
	[INVENTDIMID] ASC,
	[RECID] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [ITEMID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [STATUSISSUE]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DATEPHYSICAL]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [QTY]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [COSTAMOUNTPOSTED]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [CURRENCYCODE]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [TRANSTYPE]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [TRANSREFID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [INVOICEID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [VOUCHER]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [INVENTTRANSIDTRANSFER]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DATEEXPECTED]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DATEFINANCIAL]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [COSTAMOUNTPHYSICAL]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [INVENTTRANSID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [STATUSRECEIPT]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [PACKINGSLIPRETURNED]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [INVOICERETURNED]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [PACKINGSLIPID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [VOUCHERPHYSICAL]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [COSTAMOUNTADJUSTMENT]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [SHIPPINGDATEREQUESTED]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [SHIPPINGDATECONFIRMED]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [QTYSETTLED]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [COSTAMOUNTSETTLED]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [VALUEOPEN]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [DIRECTION]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DATESTATUS]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [COSTAMOUNTSTD]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DATECLOSED]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [PICKINGROUTEID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [INVENTTRANSIDFATHER]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [COSTAMOUNTOPERATIONS]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [ITEMBOMID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [INVENTTRANSIDRETURN]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [INVENTDIMID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [INVENTDIMFIXED]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DATEINVENT]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [CUSTVENDAC]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [TRANSCHILDREFID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [TRANSCHILDTYPE]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [REVENUEAMOUNTPHYSICAL]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [ASSETID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [TAXAMOUNTPHYSICAL]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [ASSETBOOKID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [INVENTREFTRANSID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [NONFINANCIALTRANSFERINVENTCL73]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [STORNO_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [STORNOPHYSICAL_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [INVENTDIMIDSALES_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [INVENTTRANSIDSALES_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [INVENTTRANSIDTRANSIT_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [INVENTTRANSIDDELIVERY_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [GROUPREFTYPE_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [GROUPREFID_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [COSTAMOUNTSECCURPOSTED_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [COSTAMOUNTSECCURPHYSICAL_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [COSTAMOUNTSECCURADJUSTMENT_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [DATECLOSEDSECCUR_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [QTYSETTLEDSECCUR_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [COSTAMOUNTSETTLEDSECCUR_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [VALUEOPENSECCUR_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [COSTAMOUNTSTDSECCUR_RU]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [CUSTVENDEMPLTYPE]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [TRANSTXT]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [PICKPAYTRANSTYPE]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [RASSETQTY]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [FICTRESERVEDATE]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [INVOICEEXTERNALIDCROSSDOCKING]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [SZ_DATEREGISTRATION]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((37001)) FOR [SZ_DATEREGISTRATIONTZID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [MODIFIEDDATETIME]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('?') FOR [MODIFIEDBY]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [CREATEDDATETIME]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('?') FOR [CREATEDBY]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('dat') FOR [DATAAREAID]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((1)) FOR [RECVERSION]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [SZ_DATESTATUS]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [SZ_ISFILIAL]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ((0)) FOR [SZ_ISRETAIL]
GO

ALTER TABLE [dbo].[bINVENTTRANS] ADD  DEFAULT ('') FOR [ITEMID_EXT]
GO

ALTER TABLE [dbo].[bINVENTTRANS]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO


