USE [W_test]
GO

/****** Object:  Table [dbo].[bTENDERPREREQUESTPARTICIPA31117]    Script Date: 24.05.2023 11:31:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117](
	[TENDERTABLEID] [nvarchar](20) NOT NULL,
	[TENDERREQUESTCUSTID] [nvarchar](20) NOT NULL,
	[CUSTACCOUNT] [nvarchar](20) NOT NULL,
	[PREREQUESTPARTICIPATETABLEID] [nvarchar](20) NOT NULL,
	[STATUS] [int] NOT NULL,
	[ACTIVEVERSION] [int] NOT NULL,
	[VERSION] [nvarchar](25) NOT NULL,
	[NOTE] [nvarchar](100) NOT NULL,
	[OVERHEADPERCENT] [numeric](28, 12) NOT NULL,
	[OVERHEADSUM] [numeric](28, 12) NOT NULL,
	[OVERHEADFINALVERSION] [int] NOT NULL,
	[SORTBYMINILOT] [int] NOT NULL,
	[RESPONSIBLEMANAGERID] [nvarchar](20) NOT NULL,
	[RESPONSIBLEMANAGERNAME] [nvarchar](200) NOT NULL,
	[CONTRACTGUARANT] [numeric](28, 12) NOT NULL,
	[CONTRACTGUARANTPERCENT] [numeric](28, 12) NOT NULL,
	[CONTRACTSTARTPRICE] [numeric](28, 12) NOT NULL,
	[MODIFIEDDATETIME] [datetime] NOT NULL,
	[MODIFIEDBY] [nvarchar](5) NOT NULL,
	[CREATEDDATETIME] [datetime] NOT NULL,
	[CREATEDBY] [nvarchar](5) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[RECVERSION] [int] NOT NULL,
	[RECID] [bigint] NOT NULL,
	[ALLOWNONSTANDARDROUNDING] [int] NOT NULL,
	[NOTCONTROLPRICESHIP] [int] NOT NULL,
 CONSTRAINT [I_31117TABLEIDVERSIONIDX] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[VERSION] ASC,
	[PREREQUESTPARTICIPATETABLEID] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ('') FOR [TENDERTABLEID]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ('') FOR [TENDERREQUESTCUSTID]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ('') FOR [CUSTACCOUNT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ('') FOR [PREREQUESTPARTICIPATETABLEID]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ((0)) FOR [STATUS]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ((0)) FOR [ACTIVEVERSION]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ('') FOR [VERSION]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ('') FOR [NOTE]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ((0)) FOR [OVERHEADPERCENT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ((0)) FOR [OVERHEADSUM]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ((0)) FOR [OVERHEADFINALVERSION]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ((0)) FOR [SORTBYMINILOT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ('') FOR [RESPONSIBLEMANAGERID]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ('') FOR [RESPONSIBLEMANAGERNAME]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ((0)) FOR [CONTRACTGUARANT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ((0)) FOR [CONTRACTGUARANTPERCENT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ((0)) FOR [CONTRACTSTARTPRICE]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [MODIFIEDDATETIME]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ('?') FOR [MODIFIEDBY]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [CREATEDDATETIME]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ('?') FOR [CREATEDBY]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ('dat') FOR [DATAAREAID]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ((1)) FOR [RECVERSION]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ((0)) FOR [ALLOWNONSTANDARDROUNDING]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117] ADD  DEFAULT ((0)) FOR [NOTCONTROLPRICESHIP]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31117]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO


