USE [W_test]
GO

/****** Object:  Table [dbo].[bTENDERPREREQUESTPARTICIPA31116]    Script Date: 24.05.2023 11:30:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116](
	[TENDERLINENUM] [nvarchar](30) NOT NULL,
	[PREREQUESTPARTICIPATETABLEID] [nvarchar](20) NOT NULL,
	[VERSION] [nvarchar](25) NOT NULL,
	[REQUESTPARTICIPATEPRICE] [numeric](28, 12) NOT NULL,
	[REQUESTPARTICIPATEQTY] [numeric](28, 12) NOT NULL,
	[PARTNERPRICE] [numeric](28, 12) NOT NULL,
	[CONTRACTPRICE] [numeric](28, 12) NOT NULL,
	[QUERYCOMMENTS] [nvarchar](100) NOT NULL,
	[MINIMALAMOUNTINCVAT] [numeric](28, 12) NOT NULL,
	[RIPCOMMISSIONPERCENT] [numeric](28, 12) NOT NULL,
	[FSPCOMMISSIONPERCENT] [numeric](28, 12) NOT NULL,
	[STANDARTDELIVERYCOMMISSIO30040] [numeric](28, 12) NOT NULL,
	[STANDARTDELIVERYLIMITCOMM30041] [numeric](28, 12) NOT NULL,
	[RIPLIMITCOMMISSIONPERCENT] [numeric](28, 12) NOT NULL,
	[MINIMALPRICEINCVAT] [numeric](28, 12) NOT NULL,
	[MINIMALPRICEECLVAT] [numeric](28, 12) NOT NULL,
	[RIPMINIMALCOMMISSIONPERCENT] [numeric](28, 12) NOT NULL,
	[PROFITABILITYPERCENT] [numeric](28, 12) NOT NULL,
	[MINILOTNUM] [nvarchar](30) NOT NULL,
	[MINILOTCRITERION] [nvarchar](40) NOT NULL,
	[RIPMINCOMMISSPERCENTMANUAL] [numeric](28, 12) NOT NULL,
	[GOVCONTRACTPRICE] [numeric](28, 12) NOT NULL,
	[PURCHRFQREPLYLINERECID] [bigint] NOT NULL,
	[MINMARGINPERCENT] [numeric](28, 12) NOT NULL,
	[MINREALINPUTPRICE] [numeric](28, 12) NOT NULL,
	[OFFERPRICE] [numeric](28, 12) NOT NULL,
	[PURCHPRICEMINCOMMISSPERCENT] [numeric](28, 12) NOT NULL,
	[PURCHPRICECOMPERCENTMANUAL] [numeric](28, 12) NOT NULL,
	[MODIFIEDDATETIME] [datetime] NOT NULL,
	[MODIFIEDBY] [nvarchar](5) NOT NULL,
	[CREATEDDATETIME] [datetime] NOT NULL,
	[CREATEDBY] [nvarchar](5) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[RECVERSION] [int] NOT NULL,
	[RECID] [bigint] NOT NULL,
	[FIX] [int] NOT NULL,
 CONSTRAINT [I_31116TABLEIDVERSIONLINE30001] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[TENDERLINENUM] ASC,
	[VERSION] ASC,
	[PREREQUESTPARTICIPATETABLEID] ASC,
	[MINILOTNUM] ASC,
	[MINILOTCRITERION] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ('') FOR [TENDERLINENUM]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ('') FOR [PREREQUESTPARTICIPATETABLEID]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ('') FOR [VERSION]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [REQUESTPARTICIPATEPRICE]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [REQUESTPARTICIPATEQTY]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [PARTNERPRICE]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [CONTRACTPRICE]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ('') FOR [QUERYCOMMENTS]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [MINIMALAMOUNTINCVAT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [RIPCOMMISSIONPERCENT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [FSPCOMMISSIONPERCENT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [STANDARTDELIVERYCOMMISSIO30040]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [STANDARTDELIVERYLIMITCOMM30041]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [RIPLIMITCOMMISSIONPERCENT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [MINIMALPRICEINCVAT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [MINIMALPRICEECLVAT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [RIPMINIMALCOMMISSIONPERCENT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [PROFITABILITYPERCENT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ('') FOR [MINILOTNUM]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ('') FOR [MINILOTCRITERION]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [RIPMINCOMMISSPERCENTMANUAL]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [GOVCONTRACTPRICE]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [PURCHRFQREPLYLINERECID]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [MINMARGINPERCENT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [MINREALINPUTPRICE]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [OFFERPRICE]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [PURCHPRICEMINCOMMISSPERCENT]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [PURCHPRICECOMPERCENTMANUAL]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [MODIFIEDDATETIME]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ('?') FOR [MODIFIEDBY]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [CREATEDDATETIME]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ('?') FOR [CREATEDBY]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ('dat') FOR [DATAAREAID]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((1)) FOR [RECVERSION]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116] ADD  DEFAULT ((0)) FOR [FIX]
GO

ALTER TABLE [dbo].[bTENDERPREREQUESTPARTICIPA31116]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO


