USE [W_test]
GO

/****** Object:  Table [dbo].[bTenderline]    Script Date: 24.05.2023 11:29:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[bTenderline](
	[TENDERTABLEID] [nvarchar](20) NOT NULL,
	[INVENTINTERNATIONALNAME] [nvarchar](200) NOT NULL,
	[ITEMFORMPRODUCTION] [nvarchar](100) NOT NULL,
	[ITEMDOSAGEUNITID] [nvarchar](100) NOT NULL,
	[ITEMDOSAGE] [numeric](28, 12) NOT NULL,
	[ITEMPACKING] [numeric](28, 12) NOT NULL,
	[ITEMPACKINGUNITID] [nvarchar](100) NOT NULL,
	[UNITID] [nvarchar](20) NOT NULL,
	[INVENTTRADENAME] [nvarchar](200) NOT NULL,
	[REGISTERPRICE] [numeric](28, 12) NOT NULL,
	[QUERYCOMMENTS] [nvarchar](100) NOT NULL,
	[VITAL] [int] NOT NULL,
	[BESTPRICE] [numeric](28, 12) NOT NULL,
	[DESIREDPRICE] [numeric](28, 12) NOT NULL,
	[STANDARTDELIVERYPRICE] [numeric](28, 12) NOT NULL,
	[REMAINPRICE] [numeric](28, 12) NOT NULL,
	[ITEMREQUIREDQTY] [numeric](28, 12) NOT NULL,
	[LINENUM] [nvarchar](30) NOT NULL,
	[SOURCE] [int] NOT NULL,
	[REQUESTCUSTLINENUM] [nvarchar](10) NOT NULL,
	[VENDACCOUNT] [nvarchar](20) NOT NULL,
	[PAYMTERMID] [nvarchar](20) NOT NULL,
	[ARCHIVE] [int] NOT NULL,
	[ITEMID] [nvarchar](20) NOT NULL,
	[ITEMRECALCULATEDQTY] [numeric](28, 12) NOT NULL,
	[ITEMAVAILABLEPHYSICALQTY] [numeric](28, 12) NOT NULL,
	[PRICELISTPRICE] [numeric](28, 12) NOT NULL,
	[REQUESTACCEPTED] [int] NOT NULL,
	[VENDPROPOSAL] [int] NOT NULL,
	[SELECTED] [int] NOT NULL,
	[INVENTEXPIREDATE] [datetime] NOT NULL,
	[RFQDELIVERYDATE] [datetime] NOT NULL,
	[RFQDELIVERYQTY] [numeric](28, 12) NOT NULL,
	[ITEMORIGINCOUNTRY] [nvarchar](100) NOT NULL,
	[ITEMMANUFACTURER] [nvarchar](100) NOT NULL,
	[ADDITIONALPARAMETER] [nvarchar](2000) NOT NULL,
	[ITEMUNIQUEPARAMETER] [nvarchar](100) NOT NULL,
	[REQUESTPARTICIPATEQTY] [numeric](28, 12) NOT NULL,
	[ARRIVALPRICE] [numeric](28, 12) NOT NULL,
	[COMPANYPOSITION] [int] NOT NULL,
	[REALINPUTPRICE] [numeric](28, 12) NOT NULL,
	[FACTSELLINGPRICE] [numeric](28, 12) NOT NULL,
	[SORTPRICE] [numeric](28, 12) NOT NULL,
	[LINEITEMREFRECID] [bigint] NOT NULL,
	[ARRIVALSTATUS] [int] NOT NULL,
	[PROBLEMSATDELIVERY] [int] NOT NULL,
	[REALINPUTPRICEMIN] [numeric](28, 12) NOT NULL,
	[MINREALPRICEVENDACCOUNT] [nvarchar](20) NOT NULL,
	[VITALPRICEFROMRLS] [numeric](28, 12) NOT NULL,
	[COMMENTBYPRICECHANGES] [nvarchar](100) NOT NULL,
	[EXPIREDATEINFO] [nvarchar](255) NOT NULL,
	[RLSFIRM] [nvarchar](100) NOT NULL,
	[RLSCOUNTRY] [nvarchar](100) NOT NULL,
	[PURCHREQCOMMENT] [nvarchar](100) NOT NULL,
	[MINREALINPUTPRICE] [numeric](28, 12) NOT NULL,
	[OFFERPRICE] [numeric](28, 12) NOT NULL,
	[MODIFIEDDATETIME] [datetime] NOT NULL,
	[MODIFIEDBY] [nvarchar](5) NOT NULL,
	[CREATEDDATETIME] [datetime] NOT NULL,
	[CREATEDBY] [nvarchar](5) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[RECVERSION] [int] NOT NULL,
	[RECID] [bigint] NOT NULL,
	[LINENUMINT] [int] NOT NULL,
	[NAME] [nvarchar](1000) NOT NULL,
	[COUNTRYREGIONID] [nvarchar](20) NOT NULL,
	[ESTIMATEDMARGIN] [numeric](28, 12) NOT NULL,
 CONSTRAINT [I_30969LINENUMIDIDX] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[LINENUM] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [TENDERTABLEID]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [INVENTINTERNATIONALNAME]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [ITEMFORMPRODUCTION]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [ITEMDOSAGEUNITID]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [ITEMDOSAGE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [ITEMPACKING]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [ITEMPACKINGUNITID]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [UNITID]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [INVENTTRADENAME]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [REGISTERPRICE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [QUERYCOMMENTS]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [VITAL]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [BESTPRICE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [DESIREDPRICE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [STANDARTDELIVERYPRICE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [REMAINPRICE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [ITEMREQUIREDQTY]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [LINENUM]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [SOURCE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [REQUESTCUSTLINENUM]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [VENDACCOUNT]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [PAYMTERMID]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [ARCHIVE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [ITEMID]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [ITEMRECALCULATEDQTY]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [ITEMAVAILABLEPHYSICALQTY]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [PRICELISTPRICE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [REQUESTACCEPTED]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [VENDPROPOSAL]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [SELECTED]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [INVENTEXPIREDATE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [RFQDELIVERYDATE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [RFQDELIVERYQTY]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [ITEMORIGINCOUNTRY]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [ITEMMANUFACTURER]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [ADDITIONALPARAMETER]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [ITEMUNIQUEPARAMETER]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [REQUESTPARTICIPATEQTY]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [ARRIVALPRICE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [COMPANYPOSITION]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [REALINPUTPRICE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [FACTSELLINGPRICE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [SORTPRICE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [LINEITEMREFRECID]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [ARRIVALSTATUS]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [PROBLEMSATDELIVERY]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [REALINPUTPRICEMIN]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [MINREALPRICEVENDACCOUNT]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [VITALPRICEFROMRLS]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [COMMENTBYPRICECHANGES]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [EXPIREDATEINFO]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [RLSFIRM]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [RLSCOUNTRY]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [PURCHREQCOMMENT]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [MINREALINPUTPRICE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [OFFERPRICE]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [MODIFIEDDATETIME]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('?') FOR [MODIFIEDBY]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [CREATEDDATETIME]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('?') FOR [CREATEDBY]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('dat') FOR [DATAAREAID]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((1)) FOR [RECVERSION]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [LINENUMINT]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [NAME]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ('') FOR [COUNTRYREGIONID]
GO

ALTER TABLE [dbo].[bTenderline] ADD  DEFAULT ((0)) FOR [ESTIMATEDMARGIN]
GO

ALTER TABLE [dbo].[bTenderline]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO


